exp_name: testing
checkpoint: C:\Users\retth\Dropbox\Code\Noisey-image\cae\experiments\training\checkpoint\model_1.pth
batch_every: 100
shuffle: true
dataset_path: C:\Users\retth\Desktop\yt_small_720p 
num_workers: 1
device: cuda