num_epochs: 1
batch_size: 50
learning_rate: 0.0001
resume: false
checkpoint: null
start_epoch: 1
exp_name: training
batch_every: 1
save_every: 10
epoch_every: 1
shuffle: true
dataset_path: C:\Users\retth\Desktop\Frames 
num_workers: 4
device: cuda
